services:
  - type: web
    name: yaw
    runtime: php
    region: oregon
    branch: master
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: YOUR_APP_KEY
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_USERNAME
        value: YOUR_DB_USER
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD